add clearfixes to allow using block alignment for the buttons
gocodebox/lifterlms-lite-lms-progress-tracker pull request #27
Opened 2020-08-12 19:29 UTC by thomasplevy

## Description

Fixes #26 

## How has this been tested?

+ Manually
+ Existing e2e tests

## Types of changes

+ Uses block deprecation to preserve the previous version of the block
+ Adds a wrapper element and new CSS to ensure buttons can be aligned left or right (using css floats) without breaking the layout

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

2020-08-12 19:29 UTC, thomasplevy commented
@eri-trabiccolo BIG OLD SIGH. One day old and have to add a block deprecation already!

2020-08-13 09:41 UTC, eri-trabiccolo requested changes
Minor change.
Although... We're introducing this new clearfix wrapper to always "contain" inner floating elements, right? 
If this is the only reason (as far as I understood it), we could even avoid that and use a nice trick:
```css
.wp-block-llms-lite-lms-progress-tracker {
	clear: both;
	overflow: hidden;
}
```
or
```css
.wp-block-llms-lite-lms-progress-tracker {
	clear: both;
	display: flex;
	flex-direction: column;
}
```

I'm going to push a PR with the first proposal.
see #29

2020-08-13 09:41 UTC, eri-trabiccolo commented on src/js/editor/save.js
> + * @since [version] Moved `ensureInnerBlockClassNames()` to it's own function.
```suggestion
 * @since [version] Moved `ensureInnerBlockClassNames()` to its own function.
```

2020-08-13 21:42 UTC, thomasplevy commented
Closing in favor of @eri-trabiccolo's solution in #29

2020-08-13 21:42 UTC, closed without merging